### ISSUE TITLE
Create research application

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/codewof#23]
Add application for managing research studies on codeWOF.

# Todo

- [x] Add models
- [x] Add views
- [x] Add forms
- [x] Email copy of study and consent form to user
- [x] Filter questions for user
- [x] Require login for all questions pages
- [x] Prevent user registering for study more than once
- [x] Add information how to leave study in enrolled
- [x] List questions with types

# Phase 2 (tasks to do later)

- Handle multiple studies (limit to one study at a time)
- Add researcher relationship for study
- Add admin view for study researcher

**Comment by JackMorganNZ** [comment]
Fixed in `1.0.0`.
